config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/search", to: "doctors#index", as: :search
end

app/models/doctor.rb
class Doctor
  attr_reader :first_name,
              :last_name,
              :address,
              :city,
              :state,
              :md_specialty,
              :nature_of_payment,
              :form_of_payment,
              :pharma_name,
              :year,
              :total_amount

  def initialize(data)
    @first_name        = data[:physician_first_name]
    @last_name         = data[:physician_last_name]
    @address           = data[:recipient_primary_business_street_address_line1]
    @city              = data[:recipient_city]
    @state             = data[:recipient_state]
    @md_specialty      = data[:physician_specialty]
    @nature_of_payment = data[:form_of_payment_or_transfer_of_value]
    @form_of_payment   = data[:nature_of_payment_or_transfer_of_value]
    @pharma_name       = data[:applicable_manufacturer_or_applicable_gpo_making_payment_name]
    @year              = data[:program_year]
    @total_amount      = data[:total_amount_of_payment_usdollars]
  end

  def self.service
    @service ||= SocrataService.new
  end

  def self.find_by(first_name, last_name)
    service.doctors(first_name, last_name).map { |doctor| Doctor.new(doctor) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @current_user || User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.find_by(params[:physician_first_name], params[:physician_last_name])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    flash.now.notice = "Successfully logged out"
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/doctors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6"> 
      <h2> Search for a physician by first and last names</h2>
      <%= form_for(:doctor, method: "get", url: search_path) do |f| %>
        <fieldset>
          <ol>
            <div class="form-group">
              <%= f.text_field :first_name, :placeholder => "First Name" %>
              <%= f.text_field :last_name, :placeholder => "Last Name" %>
              <%#= f.select(:state, options_for_select(us_states, "CA")) %>
              <%= f.submit "Search", search_path %>
            </div>
          </ol>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/doctors/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6"> 
      <%= form_for(:doctor, method: "get", url: search_path) do |f| %>
        <fieldset>
          <ol>
            <div class="form-group">
              <%= f.text_field :first_name, :placeholder => "First Name" %>
              <%= f.text_field :last_name, :placeholder => "Last Name" %>
              <%#= f.select(:state, options_for_select(us_states, "CA")) %>
            </div>
          </ol>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="section section-info">
  <div class="container">
    <div class="row">
      <div class="col-md-12"></div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h1 class="text-center">Login with Twitter</h1>
      </div>
      <div class="col-md-offset-3 col-md-6">
        <a href="#"><i class="beat fa fa-5x fa-fw fa-twitter-square fa-x text-success"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><span>Pharm2Doctor</span></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-ex-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <a href="#">Search</a>
        </li>
        <li>
          <a href="#">Contacts</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pharm2doctor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
          rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "navbar" %>
    <%= yield %>
    <%= render "footer" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>You're welcome</h1>

<% if current_user %>
  Hello, <%= current_user.name if current_user %>
  <%= link_to "Logout", logout_path, method: :delete %> 
<% else %> 
  <%= link_to "Login with Twitter", twitter_login_path %>
<% end %>

 <div class="section section-primary">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-left">
            <img src="/Users/Hedy/Desktop/Screen Shot 2016-06-09 at 01.21.47.png"
            class="img-responsive">
            <h1 contenteditable="true" class="text-center text-warning">Pharm2Doctor</h1>
          </div>
        </div>
      </div>
    </div>